### ISSUE TITLE
Add index.d.ts

### ISSUE THREAD

**Issue by guillaumegarcia13** [eush77/unist-util-remove#2]
### Subject of the feature

As for the other unist-util-*, please consider adding index.d.ts

**Comment by ChristianMurphy** [comment]
We are in the process of adding types, you can see some examples of types being added in
https://github.com/syntax-tree/xast-util-sitemap/pull/1, https://github.com/syntax-tree/hast-util-sanitize/pull/21, and https://github.com/syntax-tree/mdast-util-to-string/pull/5
Note that for types as a dts file, using DTSLint and/or type coverage is highly recommended.

More recently there has been a push to get types generated from JSDoc
https://github.com/wooorm/zwitch/commit/88b233db64ec7a5c791699f947ae18168febb72d  and https://github.com/wooorm/zwitch/pull/6

Either works, and a PR would be welcome!

---

Closing this issue as we don't want to keep a types tracker issue in each of the 300+ unified repos.
